### PR TITLE
Dockerfile change to allow ping

### PR DESCRIPTION
**Pull request by richmartin1169**
Updated Dockerfile to enable use of ping when running as a non-root user.

### CODE REVIEW

**Comment by aanousakis** [comment]
Is this necessary ? You can already use the ping command.

```bash
/scripts $ whoami
noip
/scripts $ ping google.com
PING google.com (216.58.213.110): 56 data bytes
64 bytes from 216.58.213.110: seq=0 ttl=42 time=51.694 ms
64 bytes from 216.58.213.110: seq=1 ttl=42 time=52.336 ms
64 bytes from 216.58.213.110: seq=2 ttl=42 time=51.791 ms```

**Comment by richmartin1169** [comment]
When I pull the current docker image the file /bin/ping is still symlinked to the busybox binary and my container logs report "ping denied (are you root?)"
I noticed in your dockerfile you install iputils to get round this but this does not appear in the final image.
The ping is used in the health check.sh script.

**Comment by aanousakis** [comment]
I made a mistake when i created a new branch. I merged 3.15 with master and it works now.

**Comment by richmartin1169** [comment]
Nice work.
This repo is much appreciated.
I'll cancel the pull request.

**Pull request closed without merging**
